// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB-fI9rw7EY6NLIgKmZKXYrRccF_Kngws',
    appId: '1:986549874924:android:4888b6bae2149ef96535c9',
    messagingSenderId: '986549874924',
    projectId: 'my-first-firebase-project-0904',
    storageBucket: 'my-first-firebase-project-0904.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkjJAqx6kB8QypipCeI0XwESl2WGCJ3js',
    appId: '1:986549874924:ios:b34983c6e125ccb76535c9',
    messagingSenderId: '986549874924',
    projectId: 'my-first-firebase-project-0904',
    storageBucket: 'my-first-firebase-project-0904.firebasestorage.app',
    androidClientId: '986549874924-1alt7oh4vcodr3r8qfhi91ksvk5epi98.apps.googleusercontent.com',
    iosClientId: '986549874924-c3h9c346d32kfd3343emn9in65eljieb.apps.googleusercontent.com',
    iosBundleId: 'com.example.dacn2',
  );

}