// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMnYPCUuzJW84hm9ASxyv2kbgun5cu3-4',
    appId: '1:986549874924:web:3d77e760691eed306535c9',
    messagingSenderId: '986549874924',
    projectId: 'my-first-firebase-project-0904',
    authDomain: 'my-first-firebase-project-0904.firebaseapp.com',
    storageBucket: 'my-first-firebase-project-0904.firebasestorage.app',
    measurementId: 'G-ZMW2SXYRTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB-fI9rw7EY6NLIgKmZKXYrRccF_Kngws',
    appId: '1:986549874924:android:1afd9ad5ed6736a66535c9',
    messagingSenderId: '986549874924',
    projectId: 'my-first-firebase-project-0904',
    storageBucket: 'my-first-firebase-project-0904.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkjJAqx6kB8QypipCeI0XwESl2WGCJ3js',
    appId: '1:986549874924:ios:fa107522fd4d132d6535c9',
    messagingSenderId: '986549874924',
    projectId: 'my-first-firebase-project-0904',
    storageBucket: 'my-first-firebase-project-0904.firebasestorage.app',
    androidClientId: '986549874924-1alt7oh4vcodr3r8qfhi91ksvk5epi98.apps.googleusercontent.com',
    iosClientId: '986549874924-aq44tbdcdg86ltmkdr05tk814mflmqah.apps.googleusercontent.com',
    iosBundleId: 'com.example.kit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkjJAqx6kB8QypipCeI0XwESl2WGCJ3js',
    appId: '1:986549874924:ios:fa107522fd4d132d6535c9',
    messagingSenderId: '986549874924',
    projectId: 'my-first-firebase-project-0904',
    storageBucket: 'my-first-firebase-project-0904.firebasestorage.app',
    androidClientId: '986549874924-1alt7oh4vcodr3r8qfhi91ksvk5epi98.apps.googleusercontent.com',
    iosClientId: '986549874924-aq44tbdcdg86ltmkdr05tk814mflmqah.apps.googleusercontent.com',
    iosBundleId: 'com.example.kit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMnYPCUuzJW84hm9ASxyv2kbgun5cu3-4',
    appId: '1:986549874924:web:8479b4d5ba19095f6535c9',
    messagingSenderId: '986549874924',
    projectId: 'my-first-firebase-project-0904',
    authDomain: 'my-first-firebase-project-0904.firebaseapp.com',
    storageBucket: 'my-first-firebase-project-0904.firebasestorage.app',
    measurementId: 'G-94BLEM68WJ',
  );

}