
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'auth_token_entity.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'auth_token_entity.g.dart';

@freezed
abstract class AuthTokenEntity with _$AuthTokenEntity {
  const factory AuthTokenEntity({
    required String accessToken,
    required String refreshToken,
  }) = _AuthTokenEntity;

  factory AuthTokenEntity.fromJson(Map<String, Object?> json) => _$AuthTokenEntityFromJson(json);
}