
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'register.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'register.g.dart';

@freezed
abstract class Register with _$Register {
  const factory Register({
    required String email,
    required String fullName,
    required String password,
    required String confirmPassword,
    required String code,
  }) = _Register;

  factory Register.fromJson(Map<String, Object?> json) => _$RegisterFromJson(json);
}