
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'send_otp.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'send_otp.g.dart';



@freezed
abstract class SendOtp with _$SendOtp {
  const factory SendOtp({
    required String email,
    required String type,
  }) = _SendOtp;

  factory SendOtp.fromJson(Map<String, Object?> json) => _$SendOtpFromJson(json);
}
