
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'auth_token_dto.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'auth_token_dto.g.dart';

@freezed
abstract class AuthTokenDto with _$AuthTokenDto {
  const factory AuthTokenDto({
    required String accessToken,
    required String refreshToken,
  }) = _AuthTokenDto;

  factory AuthTokenDto.fromJson(Map<String, Object?> json) => _$AuthTokenDtoFromJson(json);
}